"""content types, access flag, outcomes, program: quiz, flashcard_deck, matching_activity,
sequencing_activity, outcome, question_outcome, program, and Activity.access column.

What this file does: creates the plan-3a content-type tables, adds the access flag to
Activity, widens the kind vocabulary, and creates the outcome/question-outcome linking.

How it fits the project: sixth link in the chain; FKs into `activity`/`question` (0003),
`cohort` (0005). Autogenerated from SQLAlchemy models `app.content.activity_models` and
updates to `app.content.models`/`app.cohorts.models`.

Depends on: `0005_cohorts_results_audit.py`. Used by: `tests/test_migrations.py` (head "0006"),
Tasks 2-10 implementations.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-01
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # program before cohort's FK to it.
    op.create_table(
        "program",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.add_column(
        "cohort",
        sa.Column(
            "program_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("program.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    # activity: the access flag (ADR-0006) and the widened kind vocabulary.
    op.add_column(
        "activity",
        sa.Column(
            "access",
            sa.String(20),
            nullable=False,
            server_default="practice",
        ),
    )
    op.create_check_constraint(
        "ck_activity_access",
        "activity",
        "access IN ('practice', 'assessment')",
    )
    op.drop_constraint("ck_activity_kind", "activity", type_="check")
    op.create_check_constraint(
        "ck_activity_kind",
        "activity",
        "kind IN ('lesson', 'quiz', 'flashcards', 'matching', 'sequencing')",
    )
    # quiz + quiz_question over the existing question bank.
    op.create_table(
        "quiz",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("slug", sa.String(120), nullable=False, unique=True),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_table(
        "quiz_question",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "quiz_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("quiz.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "question_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("question.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.UniqueConstraint(
            "quiz_id",
            "position",
            name="uq_quiz_question_position",
        ),
        sa.UniqueConstraint(
            "quiz_id",
            "question_id",
            name="uq_quiz_question_question",
        ),
    )
    # The three JSONB payload types share one shape: id/slug/title/payload/timestamps.
    for table, payload in (
        ("flashcard_deck", "cards"),
        ("matching_activity", "pairs"),
        ("sequencing_activity", "items"),
    ):
        op.create_table(
            table,
            sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
            sa.Column("slug", sa.String(120), nullable=False, unique=True),
            sa.Column("title", sa.String(200), nullable=False),
            sa.Column(
                payload,
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=False,
            ),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.func.now(),
                nullable=False,
            ),
        )
    # outcome vocabulary + question-level tags (FR-E-07).
    op.create_table(
        "outcome",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("code", sa.String(40), nullable=False, unique=True),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_table(
        "question_outcome",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "question_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("question.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "outcome_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("outcome.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.UniqueConstraint(
            "question_id",
            "outcome_id",
            name="uq_question_outcome",
        ),
    )
    op.create_index(
        "ix_question_outcome_outcome_id",
        "question_outcome",
        ["outcome_id"],
    )


def downgrade() -> None:
    # Reverse dependency order; restore the original kind vocabulary.
    op.drop_table("question_outcome")
    op.drop_table("outcome")
    op.drop_table("sequencing_activity")
    op.drop_table("matching_activity")
    op.drop_table("flashcard_deck")
    op.drop_table("quiz_question")
    op.drop_table("quiz")
    op.drop_constraint("ck_activity_kind", "activity", type_="check")
    op.create_check_constraint(
        "ck_activity_kind",
        "activity",
        "kind IN ('lesson')",
    )
    op.drop_constraint("ck_activity_access", "activity", type_="check")
    op.drop_column("activity", "access")
    op.drop_column("cohort", "program_id")
    op.drop_table("program")
