/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/activities/{activity_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Activity
     * @description One activity's current published snapshot, answers stripped.
     *
     *     ADR-0006: students never see assessment activities — same 404 as a missing id.
     */
    get: operations["get_activity_api_v1_activities__activity_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/activities/{activity_id}/attempts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start Attempt */
    post: operations["start_attempt_api_v1_activities__activity_id__attempts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/audit-log": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Audit Log */
    get: operations["audit_log_api_v1_admin_audit_log_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Users */
    get: operations["list_users_api_v1_admin_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{user_id}/deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Deactivate User */
    post: operations["deactivate_user_api_v1_admin_users__user_id__deactivate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/{user_id}/role": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Change Role */
    patch: operations["change_role_api_v1_admin_users__user_id__role_patch"];
    trace?: never;
  };
  "/api/v1/attempts/{attempt_id}/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Grade Item */
    post: operations["grade_item_api_v1_attempts__attempt_id__items_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/attempts/{attempt_id}/submit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit Attempt */
    post: operations["submit_attempt_api_v1_attempts__attempt_id__submit_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/google/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Google Callback */
    get: operations["google_callback_api_v1_auth_google_callback_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/google/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Google Start */
    get: operations["google_start_api_v1_auth_google_start_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_v1_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/providers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Providers */
    get: operations["providers_api_v1_auth_providers_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations["register_api_v1_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cohorts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List My Cohorts */
    get: operations["list_my_cohorts_api_v1_cohorts_get"];
    put?: never;
    /** Create Cohort */
    post: operations["create_cohort_api_v1_cohorts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cohorts/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Join Cohort */
    post: operations["join_cohort_api_v1_cohorts_join_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cohorts/{cohort_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Cohort */
    get: operations["get_cohort_api_v1_cohorts__cohort_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Cohort */
    patch: operations["patch_cohort_api_v1_cohorts__cohort_id__patch"];
    trace?: never;
  };
  "/api/v1/cohorts/{cohort_id}/activities/{activity_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Activity Stats Out */
    get: operations["activity_stats_out_api_v1_cohorts__cohort_id__activities__activity_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cohorts/{cohort_id}/activities/{activity_id}.csv": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Activity Stats Csv */
    get: operations["activity_stats_csv_api_v1_cohorts__cohort_id__activities__activity_id__csv_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cohorts/{cohort_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Members */
    get: operations["list_members_api_v1_cohorts__cohort_id__members_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cohorts/{cohort_id}/members/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Member */
    delete: operations["remove_member_api_v1_cohorts__cohort_id__members__user_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cohorts/{cohort_id}/outcomes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Outcome Mastery */
    get: operations["outcome_mastery_api_v1_cohorts__cohort_id__outcomes_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cohorts/{cohort_id}/outcomes.csv": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Outcome Mastery Csv */
    get: operations["outcome_mastery_csv_api_v1_cohorts__cohort_id__outcomes_csv_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cohorts/{cohort_id}/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cohort Overview */
    get: operations["cohort_overview_api_v1_cohorts__cohort_id__overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cohorts/{cohort_id}/overview.csv": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Cohort Overview Csv */
    get: operations["cohort_overview_csv_api_v1_cohorts__cohort_id__overview_csv_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cohorts/{cohort_id}/rotate-code": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate Code */
    post: operations["rotate_code_api_v1_cohorts__cohort_id__rotate_code_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cohorts/{cohort_id}/students/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Student Detail */
    get: operations["student_detail_api_v1_cohorts__cohort_id__students__user_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/lessons/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Lesson
     * @description Serve a lesson's current published snapshot with answer keys stripped.
     *
     *     Requires both `status == "published"` and a `current_version_id` to be set — the two
     *     are kept in sync by `publish_lesson`, but checking both is cheap insurance against a
     *     lesson that's mid-migration or otherwise inconsistent.
     */
    get: operations["get_lesson_api_v1_lessons__slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me/results": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Results */
    get: operations["my_results_api_v1_me_results_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/subjects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Subjects
     * @description List subjects that have at least one published activity, with lesson and activity
     *     counts.
     */
    get: operations["list_subjects_api_v1_subjects_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/subjects/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Subject
     * @description One subject with its published lessons and practice non-lesson activities; 404s only
     *     when the subject has neither published lessons nor published practice activities.
     */
    get: operations["get_subject_api_v1_subjects__slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ActivityOut
     * @description Response for `GET /activities/{id}`: one activity's current published snapshot with
     *     answers stripped.
     */
    ActivityOut: {
      /**
       * Activity Id
       * Format: uuid
       */
      activity_id: string;
      /**
       * Content Version Id
       * Format: uuid
       */
      content_version_id: string;
      /** Kind */
      kind: string;
      /** Snapshot */
      snapshot: {
        [key: string]: unknown;
      };
    };
    /**
     * ActivityRefOut
     * @description An activity reference nested inside `SubjectDetailOut` — practice non-lesson activities
     *     only, ordered by title.
     */
    ActivityRefOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Kind */
      kind: string;
      /** Title */
      title: string;
    };
    /** ActivityRowOut */
    ActivityRowOut: {
      /**
       * Activity Id
       * Format: uuid
       */
      activity_id: string;
      /** Attempted */
      attempted: number;
      /** Below Threshold */
      below_threshold: boolean;
      /** Lesson Slug */
      lesson_slug: string | null;
      /** Mean Best Percent */
      mean_best_percent: number | null;
      /** Passed */
      passed: number;
      /** Title */
      title: string;
    };
    /** ActivityStatsOut */
    ActivityStatsOut: {
      /**
       * Activity Id
       * Format: uuid
       */
      activity_id: string;
      /** Attempts */
      attempts: number;
      /** Distribution */
      distribution: components["schemas"]["BucketOut"][];
      /** Items */
      items: components["schemas"]["ItemStatOut"][];
      /** Kind */
      kind: string;
      /** Pass Rate */
      pass_rate: number | null;
      /** Students Attempted */
      students_attempted: number;
      /** Title */
      title: string;
    };
    /** AdminUserOut */
    AdminUserOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Deactivated At */
      deactivated_at: string | null;
      /** Display Name */
      display_name: string;
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      role: components["schemas"]["UserRole"];
    };
    /** AttemptDetailOut */
    AttemptDetailOut: {
      /**
       * Activity Id
       * Format: uuid
       */
      activity_id: string;
      /**
       * Attempt Id
       * Format: uuid
       */
      attempt_id: string;
      /** Duration S */
      duration_s: number | null;
      /** Items */
      items: components["schemas"]["AttemptItemOut"][];
      /** Passed */
      passed: boolean | null;
      /** Percent */
      percent: number | null;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      /** Status */
      status: string;
      /** Submitted At */
      submitted_at: string | null;
      /** Title */
      title: string;
    };
    /** AttemptItemOut */
    AttemptItemOut: {
      /** Correct */
      correct: boolean | null;
      /** Item Key */
      item_key: string;
      /** Max Score */
      max_score: number | null;
      /** Response */
      response: {
        [key: string]: unknown;
      };
      /** Score */
      score: number | null;
    };
    /** AttemptOut */
    AttemptOut: {
      /**
       * Activity Id
       * Format: uuid
       */
      activity_id: string;
      /**
       * Content Version Id
       * Format: uuid
       */
      content_version_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Items
       * @default []
       */
      items: components["schemas"]["SavedItemOut"][];
      /** Max Score */
      max_score: number | null;
      /** Passed */
      passed: boolean | null;
      /** Percent */
      percent: number | null;
      /** Score */
      score: number | null;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      /** Status */
      status: string;
      /** Submitted At */
      submitted_at: string | null;
    };
    /** AuditOut */
    AuditOut: {
      /** Action */
      action: string;
      /** Actor Email */
      actor_email: string | null;
      /** Actor Id */
      actor_id: string | null;
      /**
       * At
       * Format: date-time
       */
      at: string;
      /** Cohort Id */
      cohort_id: string | null;
      /** Detail */
      detail: {
        [key: string]: unknown;
      };
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Ip */
      ip: string | null;
      /** Request Id */
      request_id: string | null;
      /** Target Id */
      target_id: string | null;
      /** Target Type */
      target_type: string;
    };
    /** BucketOut */
    BucketOut: {
      /** Count */
      count: number;
      /** Label */
      label: string;
    };
    /** CohortIn */
    CohortIn: {
      /** Ends On */
      ends_on?: string | null;
      /** Name */
      name: string;
      /** Starts On */
      starts_on?: string | null;
      /**
       * Threshold Percent
       * @default 70
       */
      threshold_percent: number;
    };
    /** CohortOut */
    CohortOut: {
      /** Ends On */
      ends_on: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Join Code */
      join_code: string | null;
      /** Name */
      name: string;
      /** Role */
      role: string;
      /** Starts On */
      starts_on: string | null;
      /** Student Count */
      student_count: number;
      /** Threshold Percent */
      threshold_percent: number;
    };
    /** CohortOverviewOut */
    CohortOverviewOut: {
      /** Activities */
      activities: components["schemas"]["ActivityRowOut"][];
      cohort: components["schemas"]["CohortOut"];
      /** Students */
      students: components["schemas"]["StudentRowOut"][];
    };
    /** CohortPatch */
    CohortPatch: {
      /** Ends On */
      ends_on?: string | null;
      /** Name */
      name?: string | null;
      /** Starts On */
      starts_on?: string | null;
      /** Threshold Percent */
      threshold_percent?: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ItemGradeOut */
    ItemGradeOut: {
      /** Correct */
      correct: boolean;
      /** Explanation */
      explanation: {
        [key: string]: unknown;
      } | null;
      /** Item Key */
      item_key: string;
      /** Max Score */
      max_score: number;
      /** Score */
      score: number;
    };
    /** ItemIn */
    ItemIn: {
      /** Item Key */
      item_key: string;
      /** Response */
      response: {
        [key: string]: unknown;
      };
    };
    /** ItemStatOut */
    ItemStatOut: {
      /** Answered */
      answered: number;
      /** Correct */
      correct: number;
      /** Key */
      key: string;
      /** Label */
      label: string;
      /** Percent Correct */
      percent_correct: number | null;
      /** Top Wrong */
      top_wrong: components["schemas"]["WrongOut"][];
    };
    /** JoinIn */
    JoinIn: {
      /** Code */
      code: string;
    };
    /**
     * LessonOut
     * @description Response for `GET /lessons/{slug}`: the pinned version id (what an attempt should
     *
     *     reference) plus the answer-stripped snapshot itself.
     */
    LessonOut: {
      /**
       * Activity Id
       * Format: uuid
       */
      activity_id: string;
      /**
       * Content Version Id
       * Format: uuid
       */
      content_version_id: string;
      /** Snapshot */
      snapshot: {
        [key: string]: unknown;
      };
    };
    /**
     * LessonRefOut
     * @description A lesson reference nested inside `SubjectDetailOut` (no snapshot, just enough to
     *
     *     list and link to it).
     */
    LessonRefOut: {
      /** Order */
      order: number;
      /** Slug */
      slug: string;
      /** Title */
      title: string;
    };
    /** LoginIn */
    LoginIn: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** MemberOut */
    MemberOut: {
      /** Display Name */
      display_name: string;
      /** Email */
      email: string;
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string;
      /** Last Activity At */
      last_activity_at: string | null;
      /** Role */
      role: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /** OutcomeMasteryOut */
    OutcomeMasteryOut: {
      /** Outcomes */
      outcomes: components["schemas"]["OutcomeRowOut"][];
    };
    /** OutcomeRowOut */
    OutcomeRowOut: {
      /** Answered */
      answered: number;
      /** Code */
      code: string;
      /** Percent Correct */
      percent_correct: number | null;
      /** Questions */
      questions: number;
      /** Students */
      students: components["schemas"]["OutcomeStudentOut"][];
      /** Students Below Threshold */
      students_below_threshold: number;
      /** Title */
      title: string;
    };
    /** OutcomeStudentOut */
    OutcomeStudentOut: {
      /** Answered */
      answered: number;
      /** Display Name */
      display_name: string;
      /** Percent Correct */
      percent_correct: number | null;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /** RegisterIn */
    RegisterIn: {
      /** Display Name */
      display_name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** ResultOut */
    ResultOut: {
      /**
       * Activity Id
       * Format: uuid
       */
      activity_id: string;
      /** Activity Title */
      activity_title: string;
      /**
       * Attempt Id
       * Format: uuid
       */
      attempt_id: string;
      /** Lesson Slug */
      lesson_slug: string | null;
      /** Max Score */
      max_score: number | null;
      /** Passed */
      passed: boolean | null;
      /** Percent */
      percent: number | null;
      /** Score */
      score: number | null;
      /** Submitted At */
      submitted_at: string | null;
    };
    /** RoleIn */
    RoleIn: {
      role: components["schemas"]["UserRole"];
    };
    /** SavedItemOut */
    SavedItemOut: {
      /** Correct */
      correct: boolean | null;
      /** Item Key */
      item_key: string;
      /** Max Score */
      max_score: number | null;
      /** Response */
      response: {
        [key: string]: unknown;
      };
      /** Score */
      score: number | null;
    };
    /** StudentDetailOut */
    StudentDetailOut: {
      /** Attempts */
      attempts: components["schemas"]["AttemptDetailOut"][];
      /** Results */
      results: components["schemas"]["StudentResultOut"][];
      student: components["schemas"]["MemberOut"];
    };
    /** StudentResultOut */
    StudentResultOut: {
      /**
       * Activity Id
       * Format: uuid
       */
      activity_id: string;
      /** Attempts */
      attempts: number;
      /** Best Percent */
      best_percent: number | null;
      /** First Passed At */
      first_passed_at: string | null;
      /** Latest Percent */
      latest_percent: number | null;
      /** Lesson Slug */
      lesson_slug: string | null;
      /** Mastery */
      mastery: string;
      /** Time Spent S */
      time_spent_s: number;
      /** Title */
      title: string;
    };
    /** StudentRowOut */
    StudentRowOut: {
      /** Attempted */
      attempted: number;
      /** Below Threshold */
      below_threshold: boolean;
      /** Display Name */
      display_name: string;
      /** Email */
      email: string;
      /** Last Activity At */
      last_activity_at: string | null;
      /** Mean Best Percent */
      mean_best_percent: number | null;
      /** Passed */
      passed: number;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /**
     * SubjectDetailOut
     * @description Response for `GET /subjects/{slug}`: one subject with its published lessons and practice
     *     non-lesson activities.
     */
    SubjectDetailOut: {
      /**
       * Activities
       * @default []
       */
      activities: components["schemas"]["ActivityRefOut"][];
      /** Lessons */
      lessons: components["schemas"]["LessonRefOut"][];
      /** Slug */
      slug: string;
      /** Summary */
      summary: string | null;
      /** Title */
      title: string;
    };
    /**
     * SubjectOut
     * @description One row of `GET /subjects`: a subject plus its published-lesson count and activity count.
     */
    SubjectOut: {
      /** Activity Count */
      activity_count: number;
      /** Lesson Count */
      lesson_count: number;
      /** Order */
      order: number;
      /** Slug */
      slug: string;
      /** Title */
      title: string;
    };
    /** UserOut */
    UserOut: {
      /** Display Name */
      display_name: string;
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      role: components["schemas"]["UserRole"];
    };
    /** UserPage */
    UserPage: {
      /** Items */
      items: components["schemas"]["AdminUserOut"][];
      /** Next Cursor */
      next_cursor: string | null;
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: "student" | "educator" | "admin";
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WrongOut */
    WrongOut: {
      /** Count */
      count: number;
      /** Option */
      option: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_activity_api_v1_activities__activity_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        activity_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActivityOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_attempt_api_v1_activities__activity_id__attempts_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        activity_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttemptOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  audit_log_api_v1_admin_audit_log_get: {
    parameters: {
      query?: {
        actor_id?: string | null;
        action?: string | null;
        target_id?: string | null;
        since?: string | null;
        until?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_users_api_v1_admin_users_get: {
    parameters: {
      query?: {
        q?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  deactivate_user_api_v1_admin_users__user_id__deactivate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  change_role_api_v1_admin_users__user_id__role_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RoleIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  grade_item_api_v1_attempts__attempt_id__items_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        attempt_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ItemGradeOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_attempt_api_v1_attempts__attempt_id__submit_post: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path: {
        attempt_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttemptOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  google_callback_api_v1_auth_google_callback_get: {
    parameters: {
      query?: {
        code?: string | null;
        state?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  google_start_api_v1_auth_google_start_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
    };
  };
  providers_api_v1_auth_providers_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: boolean;
          };
        };
      };
    };
  };
  register_api_v1_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_my_cohorts_api_v1_cohorts_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CohortOut"][];
        };
      };
    };
  };
  create_cohort_api_v1_cohorts_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CohortIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CohortOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  join_cohort_api_v1_cohorts_join_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CohortOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_cohort_api_v1_cohorts__cohort_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cohort_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CohortOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_cohort_api_v1_cohorts__cohort_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cohort_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CohortPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CohortOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  activity_stats_out_api_v1_cohorts__cohort_id__activities__activity_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        activity_id: string;
        cohort_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActivityStatsOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  activity_stats_csv_api_v1_cohorts__cohort_id__activities__activity_id__csv_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        activity_id: string;
        cohort_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_members_api_v1_cohorts__cohort_id__members_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cohort_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_member_api_v1_cohorts__cohort_id__members__user_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
        cohort_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  outcome_mastery_api_v1_cohorts__cohort_id__outcomes_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cohort_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutcomeMasteryOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  outcome_mastery_csv_api_v1_cohorts__cohort_id__outcomes_csv_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cohort_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cohort_overview_api_v1_cohorts__cohort_id__overview_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cohort_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CohortOverviewOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cohort_overview_csv_api_v1_cohorts__cohort_id__overview_csv_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cohort_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rotate_code_api_v1_cohorts__cohort_id__rotate_code_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cohort_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CohortOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  student_detail_api_v1_cohorts__cohort_id__students__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
        cohort_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StudentDetailOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  get_lesson_api_v1_lessons__slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LessonOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_results_api_v1_me_results_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResultOut"][];
        };
      };
    };
  };
  list_subjects_api_v1_subjects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubjectOut"][];
        };
      };
    };
  };
  get_subject_api_v1_subjects__slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubjectDetailOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
